export interface AzureLanguage {
  code: string   // Azure Translator short code
  bcp47: string  // BCP-47 locale
  label: string  // Human-readable name
}

/**
 * Subset of Azure Translator supported languages.
 * Source: https://learn.microsoft.com/en-us/azure/ai-services/translator/language-support
 * This is a static list — Azure rarely adds/removes languages.
 */
export const AZURE_TRANSLATION_LANGUAGES: AzureLanguage[] = [
  { code: 'af', bcp47: 'af', label: 'Afrikaans' },
  { code: 'am', bcp47: 'am', label: 'Amharic' },
  { code: 'ar', bcp47: 'ar', label: 'Arabic' },
  { code: 'as', bcp47: 'as', label: 'Assamese' },
  { code: 'az', bcp47: 'az', label: 'Azerbaijani' },
  { code: 'ba', bcp47: 'ba', label: 'Bashkir' },
  { code: 'bg', bcp47: 'bg', label: 'Bulgarian' },
  { code: 'bn', bcp47: 'bn', label: 'Bangla' },
  { code: 'bo', bcp47: 'bo', label: 'Tibetan' },
  { code: 'bs', bcp47: 'bs', label: 'Bosnian (Serbo-Croatian)' },
  { code: 'ca', bcp47: 'ca', label: 'Catalan' },
  { code: 'cs', bcp47: 'cs', label: 'Czech' },
  { code: 'cy', bcp47: 'cy', label: 'Welsh' },
  { code: 'da', bcp47: 'da', label: 'Danish' },
  { code: 'de', bcp47: 'de', label: 'German' },
  { code: 'el', bcp47: 'el', label: 'Greek' },
  { code: 'en', bcp47: 'en', label: 'English' },
  { code: 'es', bcp47: 'es', label: 'Spanish' },
  { code: 'et', bcp47: 'et', label: 'Estonian' },
  { code: 'eu', bcp47: 'eu', label: 'Basque' },
  { code: 'fa', bcp47: 'fa', label: 'Persian' },
  { code: 'fi', bcp47: 'fi', label: 'Finnish' },
  { code: 'fil', bcp47: 'fil', label: 'Filipino' },
  { code: 'fj', bcp47: 'fj', label: 'Fijian' },
  { code: 'fo', bcp47: 'fo', label: 'Faroese' },
  { code: 'fr', bcp47: 'fr', label: 'French' },
  { code: 'ga', bcp47: 'ga', label: 'Irish' },
  { code: 'gl', bcp47: 'gl', label: 'Galician' },
  { code: 'gu', bcp47: 'gu', label: 'Gujarati' },
  { code: 'ha', bcp47: 'ha', label: 'Hausa' },
  { code: 'he', bcp47: 'he', label: 'Hebrew' },
  { code: 'hi', bcp47: 'hi', label: 'Hindi' },
  { code: 'hr', bcp47: 'hr', label: 'Croatian (Serbo-Croatian)' },
  { code: 'hsb', bcp47: 'hsb', label: 'Upper Sorbian' },
  { code: 'ht', bcp47: 'ht', label: 'Haitian Creole' },
  { code: 'hu', bcp47: 'hu', label: 'Hungarian' },
  { code: 'hy', bcp47: 'hy', label: 'Armenian' },
  { code: 'id', bcp47: 'id', label: 'Indonesian' },
  { code: 'ig', bcp47: 'ig', label: 'Igbo' },
  { code: 'ikt', bcp47: 'ikt', label: 'Inuinnaqtun' },
  { code: 'is', bcp47: 'is', label: 'Icelandic' },
  { code: 'it', bcp47: 'it', label: 'Italian' },
  { code: 'iu', bcp47: 'iu', label: 'Inuktitut' },
  { code: 'ja', bcp47: 'ja', label: 'Japanese' },
  { code: 'ka', bcp47: 'ka', label: 'Georgian' },
  { code: 'kk', bcp47: 'kk', label: 'Kazakh' },
  { code: 'km', bcp47: 'km', label: 'Khmer' },
  { code: 'kn', bcp47: 'kn', label: 'Kannada' },
  { code: 'ko', bcp47: 'ko', label: 'Korean' },
  { code: 'ku', bcp47: 'ku', label: 'Kurdish (Central)' },
  { code: 'ky', bcp47: 'ky', label: 'Kyrgyz' },
  { code: 'lo', bcp47: 'lo', label: 'Lao' },
  { code: 'lt', bcp47: 'lt', label: 'Lithuanian' },
  { code: 'lv', bcp47: 'lv', label: 'Latvian' },
  { code: 'lzh', bcp47: 'lzh', label: 'Chinese (Literary)' },
  { code: 'mg', bcp47: 'mg', label: 'Malagasy' },
  { code: 'mi', bcp47: 'mi', label: 'Te reo Māori' },
  { code: 'mk', bcp47: 'mk', label: 'Macedonian' },
  { code: 'ml', bcp47: 'ml', label: 'Malayalam' },
  { code: 'mn', bcp47: 'mn', label: 'Mongolian (Cyrillic)' },
  { code: 'mr', bcp47: 'mr', label: 'Marathi' },
  { code: 'ms', bcp47: 'ms', label: 'Malay' },
  { code: 'mt', bcp47: 'mt', label: 'Maltese' },
  { code: 'my', bcp47: 'my', label: 'Myanmar (Burmese)' },
  { code: 'nb', bcp47: 'nb', label: 'Norwegian' },
  { code: 'ne', bcp47: 'ne', label: 'Nepali' },
  { code: 'nl', bcp47: 'nl', label: 'Dutch' },
  { code: 'or', bcp47: 'or', label: 'Odia' },
  { code: 'pa', bcp47: 'pa', label: 'Punjabi' },
  { code: 'pl', bcp47: 'pl', label: 'Polish' },
  { code: 'ps', bcp47: 'ps', label: 'Pashto' },
  { code: 'pt', bcp47: 'pt', label: 'Portuguese' },
  { code: 'ro', bcp47: 'ro', label: 'Romanian' },
  { code: 'ru', bcp47: 'ru', label: 'Russian' },
  { code: 'rw', bcp47: 'rw', label: 'Kinyarwanda' },
  { code: 'sk', bcp47: 'sk', label: 'Slovak' },
  { code: 'sl', bcp47: 'sl', label: 'Slovenian' },
  { code: 'sm', bcp47: 'sm', label: 'Samoan' },
  { code: 'sn', bcp47: 'sn', label: 'Shona' },
  { code: 'so', bcp47: 'so', label: 'Somali' },
  { code: 'sq', bcp47: 'sq', label: 'Albanian' },
  { code: 'si', bcp47: 'si', label: 'Sinhala' },
  { code: 'sr', bcp47: 'sr', label: 'Serbian (Serbo-Croatian)' },
  { code: 'st', bcp47: 'st', label: 'Sesotho' },
  { code: 'sv', bcp47: 'sv', label: 'Swedish' },
  { code: 'sw', bcp47: 'sw', label: 'Swahili' },
  { code: 'ta', bcp47: 'ta', label: 'Tamil' },
  { code: 'te', bcp47: 'te', label: 'Telugu' },
  { code: 'th', bcp47: 'th', label: 'Thai' },
  { code: 'ti', bcp47: 'ti', label: 'Tigrinya' },
  { code: 'tk', bcp47: 'tk', label: 'Turkmen' },
  { code: 'to', bcp47: 'to', label: 'Tongan' },
  { code: 'tr', bcp47: 'tr', label: 'Turkish' },
  { code: 'tt', bcp47: 'tt', label: 'Tatar' },
  { code: 'ty', bcp47: 'ty', label: 'Tahitian' },
  { code: 'ug', bcp47: 'ug', label: 'Uyghur' },
  { code: 'uk', bcp47: 'uk', label: 'Ukrainian' },
  { code: 'ur', bcp47: 'ur', label: 'Urdu' },
  { code: 'uz', bcp47: 'uz', label: 'Uzbek' },
  { code: 'vi', bcp47: 'vi', label: 'Vietnamese' },
  { code: 'xh', bcp47: 'xh', label: 'Xhosa' },
  { code: 'yo', bcp47: 'yo', label: 'Yoruba' },
  { code: 'yue', bcp47: 'yue', label: 'Cantonese (Traditional)' },
  { code: 'zh-Hans', bcp47: 'zh-Hans', label: 'Chinese (Simplified)' },
  { code: 'zh-Hant', bcp47: 'zh-Hant', label: 'Chinese (Traditional)' },
  { code: 'zu', bcp47: 'zu', label: 'Zulu' },
]
